import type { Metadata } from "next";
import {
  Instrument_Serif,
  Newsreader,
  IBM_Plex_Mono,
  Caveat,
} from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";

const display = Instrument_Serif({
  variable: "--font-display",
  display: "swap",
  subsets: ["latin"],
  weight: "400",
});

const body = Newsreader({
  variable: "--font-body",
  display: "swap",
  subsets: ["latin"],
});

const label = IBM_Plex_Mono({
  variable: "--font-label",
  display: "swap",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const margin = Caveat({
  variable: "--font-margin",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${display.variable} ${body.variable} ${label.variable} ${margin.variable} antialiased`}
      >
        <ThemeProvider attribute="data-theme" defaultTheme="light">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}